---
- hosts: all
  become: yes
  vars:
    - ansible_connection: ssh
    - ansible_user: ubuntu
    - domain: 
    - ansible_port: 22
    - mysql_port: 3306
    - mysql_root_password: root
    - php_version:
    # Wordpress config
    - auto_up_disable: true
    - core_update_level: true
    # For WP-CLI
    - root_bin: /usr/local/bin
    - wpuser: supervisor
    - wpmail:
    # For Certbot/LetsEncrypt
    - certbot_mail: 
  roles:
    - static
    - fail2ban
    - php
    - mysql
    - wordpress
    - ufw
    - certbot
